
////
This file is generated! See etc/fields.yml and scripts/generate_field_docs.py
////

[[exported-fields]]
== Exported fields

This document describes the fields that are exported by the
httpbeat. They are grouped in the
following categories:

* <<exported-fields-env>>
* <<exported-fields-httpbeat>>

[[exported-fields-env]]
=== Common fields fields

Contains common fields available in all event types.



==== beat.name

The name of the Beat sending the log messages. If the shipper name is set in the configuration file, then that value is used. If it is not set, the hostname is used.


==== beat.hostname

The hostname as returned by the operating system on which the Beat is running.


==== @timestamp

type: date

example: 2015-01-24 14:06:05.071000

format: YYYY-MM-DDTHH:MM:SS.milliZ

required: True

The timestamp when the HTTP url was called. The precision is in milliseconds. The timezone is UTC.


==== type

Always httpbeat


[[exported-fields-httpbeat]]
=== Httpbeat information fields

Contains http request and response information



=== request fields


==== url

type: string

URL endpoint called by by Httpbeat.


==== method

type: string

HTTP method used by Httpbeat to call the URL endpoint.


==== body

type: string

HTTP request body passed to the URL endpoint.


=== headers fields

HTTP headers send to the URL endpoint.



=== response fields


==== code

type: string

HTTP status code returned by the URL endpoint.


==== body

type: string

HTTP response body returned by the URL endpoint.


=== headers fields

HTTP response headers send by the URL endpoint.



